#incredible testing is happening here


import unittest
from unittest.mock import patch, MagicMock

#not working tests
# from tests.test_1 import Test1 inanılmaz bir çzöüm yeni testler error verdi inanılmaz bir flamingo

#tasks and tests just work right